name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            php-version: "5.3"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "5.4"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "5.5"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "5.6"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: windows-latest
            php-version: "5.6"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "7.0"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "7.1"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "7.2"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "7.3"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "7.4"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: windows-latest
            php-version: "7.4"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "8.0"
            phpunit-flags: "--configuration phpunit-4.xml"
          - os: ubuntu-latest
            php-version: "8.1"
            phpunit-flags: "--configuration phpunit-10.xml"
          - os: ubuntu-latest
            php-version: "8.2"
            phpunit-flags: "--configuration phpunit-10.xml"
          - os: windows-latest
            php-version: "8.2"
            phpunit-flags: "--configuration phpunit-10.xml"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        run: composer --ansi --no-interaction --no-progress --optimize-autoloader update
      - name: Create debug file
        run: php ./bin/create-idnamap --debug test/assets/IdnaMappingTable.txt -
      - name: Run PHPUnit
        run: composer --ansi --no-interaction run-script test -- ${{ matrix.phpunit-flags }}
